jobs:
  - ${{ each module in parameters.modules }}:
    - job:
      displayName: ${{ format('iOS {0}', module) }}
      pool:
        vmImage: internal-macos-10.15
      steps:
      - task: Xcode@5
        displayName: Analyze
        inputs:
          actions: analyze
          configuration: Debug
          sdk: iphonesimulator
          xcWorkspacePath: AppCenter.xcworkspace
          scheme: '${{ module }} iOS Framework'
          xcodeVersion: specifyPath
          xcodeDeveloperDir: '$(XCODE_PATH)'
          destinationPlatformOption: iOS
          destinationSimulators: 'iPhone 11'

      - task: Xcode@5
        displayName: Test
        inputs:
          actions: test
          configuration: Debug
          sdk: iphonesimulator
          xcWorkspacePath: AppCenter.xcworkspace
          scheme: '${{ module }} iOS Framework'
          xcodeVersion: specifyPath
          xcodeDeveloperDir: '$(XCODE_PATH)'
          destinationPlatformOption: iOS
          destinationSimulators: 'iPhone 11'
          publishJUnitResults: true
        timeoutInMinutes: 10

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Diagnostic Reports'
        inputs:
          PathtoPublish: /Users/runner/Library/Logs/DiagnosticReports
          ArtifactName: 'Test Diagnostic Reports'
        condition: failed()

      - bash: 'bash <(curl -s https://codecov.io/bash) -X gcov -cF iOS'
        displayName: 'Upload Coverage Report to Codecov'

